export default {
  myHotelDetailsList: state => state.myHotelDetailsList,
  updateHotelDetilsObj: state => state.updateHotelDetilsObj,
  provinceHotelDataList: state => state.provinceHotelDataList,
  cityHotelDataList: state => state.cityHotelDataList,
  countyHotelDataList: state => state.countyHotelDataList,
  recommendTypeList: state => state.recommendTypeList,
  hotelQueryRecommendList: state => state.hotelQueryRecommendList,
  hotelIntroduceTypeList: state => state.hotelIntroduceTypeList,
  hotelImageList: state => state.hotelImageList,
  hotelImageTypeList: state => state.hotelImageTypeList,
  hotelPolicyList: state => state.hotelPolicyList,
  updateHotelImageObj: state => state.updateHotelImageObj,
  updateHotelPolicyObj: state => state.updateHotelPolicyObj,
  hotelThemeTypeList: state => state.hotelThemeTypeList,
  hotelThemeList: state => state.hotelThemeList,
  hotelIconList: state => state.hotelIconList,
  hotelIconGalleryList: state => state.hotelIconGalleryList,
}
